### ISSUE TITLE
Bug: Akismet comment nonce is not automatically disabled

### ISSUE THREAD

**Issue by Kalfer** [wpsharks/comet-cache#642] opened 2015-12-25 12:44 UTC
Hey there

I upgraded to Pro v151220 ZenCache, and I found that the Akismet (3.1.6) plugin also causes the issue #601.

Thank you

**Comment by raamdev** [comment] 2015-12-26 13:30
@Kalfer ZenCache Pro v151220 automatically detects when the HTML contains `_wpnonce` or `akismet_comment_nonce` and prevents that page from being cached. When this happens, you should see a note at the very bottom of the source code (when you View Source on the page) that indicates as much (assuming you have ZenCache HTML Notes enabled in **ZenCache → Plugin Options → Enable/Disable**). 

Is that not happening? Can you explain the problem you're having with the Akismet plugin and ZenCache?

**Comment by Kalfer** [comment] 2015-12-26 16:57
Yes, I saw that message at the end of my web source code.

Now I have Akismet disabled. Is there any alternative to Akismet?

Thanks

**Comment by raamdev** [comment] 2015-12-26 17:26
@Kalfer ZenCache is supposed to disable the Akismet nonce when it detects that Akismet is active (see [this line](https://github.com/websharks/zencache-pro/commit/5a28f4ce696fad1976d3ccf4579b4fcbafea1217#diff-80c3f899e9a4e8c5ee77be429a019f08R500)), but for some reason that's not working as expected. I just confirmed this on my own site and I'm still researching.

You should definitely be able to use Akismet and ZenCache together.

**Comment by raamdev** [comment] 2015-12-26 18:27
### Problem Found: Akismet Bug

This is actually a bug in the way Akismet checks the value of `$akismet_comment_nonce_option` on [this line](https://plugins.trac.wordpress.org/browser/akismet/tags/3.1.6/class.akismet.php?rev=1316570#L34). 

Akismet is using `==` (simple equality operator) instead of `===` (strict type comparison operator) when checking if `$akismet_comment_nonce_option == ''`, so when a filter sets the value of `$akismet_comment_nonce_option` to boolean `FALSE`, **the conditional still evaluates to true** because `== ''` is the same as `== FALSE`.

If that line in Akismet is changed to `$akismet_comment_nonce_option === ''`, then filtering `$akismet_comment_nonce_option` to return boolean `FALSE` works as expected, disabling that option.

### Akismet Bug Report Opened

I've opened an Akismet bug report here: https://plugins.trac.wordpress.org/ticket/2467

**Comment by raamdev** [comment] 2015-12-26 18:28
### Temporary Fix for Site Owners

You can use an [MU-Plugin](http://codex.wordpress.org/Must_Use_Plugins) to tell Akismet to disable the Akismet Nonce, which will allow ZenCache to continue caching pages even while Akismet is enabled. (This was the intended behavior all along, but due to the bug described above, it's not working as expected in the latest ZenCache release. This MU-Plugin returns a value to Akismet that works around the bug.)

Create this file and directory:
`wp-content/mu-plugins/zc-disable-akismet-nonce.php`

``` php
<?php
/*
Plugin Name: Disable Akismet Comment Nonce
Description: Disables the Akismet comment nonce; required for ZenCache
Author: WebSharks, Inc.
Version: 1.0
Author URI: http://zencache.com/
*/
add_filter('akismet_comment_nonce', function() {
    return 'not-true'; // MUST return a string literal; must not be 'true'. See http://bit.ly/1YItpdE
}, PHP_INT_MAX);
```

**Comment by raamdev** [comment] 2015-12-26 18:28
### How ZenCache can resolve this in the next release

If Akismet does not fix this issue by the next ZenCache release, we can temporarily work around this issue by returning something like `'not-true'` (or `'0'`--as a string literal--, but that might be confusing and get refactored to return `0` which would introduce this issue again) instead of boolean `FALSE`.

The nice thing about returning something like `'not-true'` is that it would continue to work as expected even after Akismet fixes the above issue.

**Comment by raamdev** [comment] 2015-12-26 19:12
**EDIT:** Added `PHP_INT_MAX` to `add_filter()` in **Temporary Workaround** above.

**Comment by raamdev** [comment] 2015-12-27 19:12
Note that this is not be changed/fixed in Akismet for backwards compatibility reasons; see [this comment](https://plugins.trac.wordpress.org/ticket/2467#comment:3):

> This is mostly a case of missing documentation meeting backwards compatibility.
> In the interest of not breaking any implementations that have been written in the last five years, I've left the code as is but added explanatory documentation in r1316691. To disable the Akismet comment nonce, return any string value that is not `'true'` or `''` for the `'akismet_comment_nonce'` filter. A good option would be the reason why the filter is disabled, like `'disabled-by-zencache'`.
> 
> The reason that Akismet will still include the comment nonce even if the filter returns false is because originally, the nonce was controlled solely by the `akismet_comment_nonce` option, which could be set to (string) `'true'` or (string) `'false'`. If the `get_option()` call returned (boolean) `false`, that meant that no value had been set, so Akismet should just choose whatever the default behavior was, which meant including the nonce. The check for `$akismet_comment_nonce_option == ''` was meant to cover this case (but should have originally been `$akismet_comment_nonce_option === false`).

---

All that remains to close this issue is to change ZenCache so that it returns (string) `'disabled-by-zencache'` instead of (boolean) `false`.

**Comment by raamdev** [comment] 2015-12-31 16:53
Next Pro Release Changelog:
- **Akismet Compatibility**: Fixed a bug with Akismet compatibility where ZenCache was not properly disabling the Akismet Comment Nonce, which resulted in pages being unnecessarily excluded from the cache due to the presence of the `akismet_comment_nonce` in the markup. Props @Kalfer. See [Issue #642](https://github.com/websharks/zencache/issues/642).

**Closed as completed by raamdev** 2015-12-31 16:53 UTC
Labels: bug

**Comment by raamdev** [comment] 2016-01-03 20:37
**ZenCache Pro v160103** has been released and includes changes from this GitHub Issue. See the [v160103 announcement](http://zencache.com/zencache-pro-v160103-now-available/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#642).
