### ISSUE TITLE
multisite trailing / slash issue

### ISSUE THREAD

**Issue by gwfc** [wpsharks/comet-cache#912] opened 2017-08-31 16:05 UTC
Hi, this is in reference to https://github.com/websharks/comet-cache/issues/554

Watch this 3 min video: https://www.screencast.com/t/GU4EYbq3u

and the end of a live chat with wpmudev which helped to isolate the issue to that module in comet cache causing the above issue in the video (I would say it is pretty significant and hidden issue for multisites):

"

I use comet cache network activated. see here https://www.screencast.com/t/5d2gsVMpQo0 possible reason? | I use comet cache network activated. see here https://www.screencast.com/t/5d2gsVMpQo0 possible reason? | I use comet cache network activated. see here https://www.screencast.com/t/5d2gsVMpQo0 |   | possible reason? |   |   |  
-- | -- | -- | -- | -- | -- | -- | --
I use comet cache network activated. see here https://www.screencast.com/t/5d2gsVMpQo0 possible reason? | I use comet cache network activated. see here https://www.screencast.com/t/5d2gsVMpQo0 |   | possible reason? |   |  
I use comet cache network activated. see here https://www.screencast.com/t/5d2gsVMpQo0 |  
possible reason? |  
 
 
 
Majid Hamdani09:55:19 pm it could be yes ! add # before it, so it will be commented and check |   |   | Majid Hamdani | 09:55:19 pm |   |   |   | it could be yes ! add # before it, so it will be commented and check | it could be yes ! |   | add # before it, so it will be commented and check |   |   |  
 
  | Majid Hamdani | 09:55:19 pm |  
 
  | it could be yes ! add # before it, so it will be commented and check | it could be yes ! |   | add # before it, so it will be commented and check |   |  
it could be yes ! |  
add # before it, so it will be commented and check |  
 
 
 
greg09:56:47 pm ok...did it...let me test it now commenting out did not work...now i just turned that whole module off on the network https://www.screencast.com/t/xV6w5bQHJgy10:02:20 pmretrying...just a secthat worked actually10:03:04 pmif you read that module...what do you think about leaving it off generally?and also this is working as needed too with the other .htaccess issue i had open in my last actual support ticket http://shopcharlieandeva.com/wc-api/v210:06:10 pmcan you click on that and tell me if the trailing slash appears on your end or not after you click it?if it is gone then that is good |   |   | greg | 09:56:47 pm |   |   |   | ok...did it...let me test it now commenting out did not work...now i just turned that whole module off on the network https://www.screencast.com/t/xV6w5bQHJgy10:02:20 pmretrying...just a secthat worked actually10:03:04 pmif you read that module...what do you think about leaving it off generally?and also this is working as needed too with the other .htaccess issue i had open in my last actual support ticket http://shopcharlieandeva.com/wc-api/v210:06:10 pmcan you click on that and tell me if the trailing slash appears on your end or not after you click it?if it is gone then that is good | ok...did it...let me test it now |   | commenting out did not work...now i just turned that whole module off on the network https://www.screencast.com/t/xV6w5bQHJgy | 10:02:20 pm | retrying...just a sec |   | that worked actually | 10:03:04 pm | if you read that module...what do you think about leaving it off generally? |   | and also this is working as needed too with the other .htaccess issue i had open in my last actual support ticket http://shopcharlieandeva.com/wc-api/v2 | 10:06:10 pm | can you click on that and tell me if the trailing slash appears on your end or not after you click it? |   | if it is gone then that is good |   |   |  
 
  | greg | 09:56:47 pm |  
 
  | ok...did it...let me test it now commenting out did not work...now i just turned that whole module off on the network https://www.screencast.com/t/xV6w5bQHJgy10:02:20 pmretrying...just a secthat worked actually10:03:04 pmif you read that module...what do you think about leaving it off generally?and also this is working as needed too with the other .htaccess issue i had open in my last actual support ticket http://shopcharlieandeva.com/wc-api/v210:06:10 pmcan you click on that and tell me if the trailing slash appears on your end or not after you click it?if it is gone then that is good | ok...did it...let me test it now |   | commenting out did not work...now i just turned that whole module off on the network https://www.screencast.com/t/xV6w5bQHJgy | 10:02:20 pm | retrying...just a sec |   | that worked actually | 10:03:04 pm | if you read that module...what do you think about leaving it off generally? |   | and also this is working as needed too with the other .htaccess issue i had open in my last actual support ticket http://shopcharlieandeva.com/wc-api/v2 | 10:06:10 pm | can you click on that and tell me if the trailing slash appears on your end or not after you click it? |   | if it is gone then that is good |   |  
ok...did it...let me test it now |  
commenting out did not work...now i just turned that whole module off on the network https://www.screencast.com/t/xV6w5bQHJgy | 10:02:20 pm
retrying...just a sec |  
that worked actually | 10:03:04 pm
if you read that module...what do you think about leaving it off generally? |  
and also this is working as needed too with the other .htaccess issue i had open in my last actual support ticket http://shopcharlieandeva.com/wc-api/v2 | 10:06:10 pm
can you click on that and tell me if the trailing slash appears on your end or not after you click it? |  
if it is gone then that is good |  
 
 
 
Majid Hamdani10:07:43 pm it's gone |   |   | Majid Hamdani | 10:07:43 pm |   |   |   | it's gone | it's gone |   |   |  
 
  | Majid Hamdani | 10:07:43 pm |  
 
  | it's gone | it's gone |   |  
it's gone |  
 
 
 
greg10:07:50 pm great. |   |   | greg | 10:07:50 pm |   |   |   | great. | great. |   |   |  
 
  | greg | 10:07:50 pm |  
 
  | great. | great. |   |  
great. |  
 
 
 
Majid Hamdani10:08:18 pm http://take.ms/gIOPC |   |   | Majid Hamdani | 10:08:18 pm |   |   |   | http://take.ms/gIOPC | http://take.ms/gIOPC |   |   |  
 
  | Majid Hamdani | 10:08:18 pm |  
 
  | http://take.ms/gIOPC | http://take.ms/gIOPC |   |  
http://take.ms/gIOPC |  
 
 
 
greg10:09:10 pm great yea... that being said, comet cache recommends this on but it obviously causes that issue. see here https://www.screencast.com/t/GjBSMP3ado you see any benefit to have in on yes or no? |   |   | greg | 10:09:10 pm |   |   |   | great yea... that being said, comet cache recommends this on but it obviously causes that issue. see here https://www.screencast.com/t/GjBSMP3ado you see any benefit to have in on yes or no? | great yea... |   | that being said, comet cache recommends this on but it obviously causes that issue. see here https://www.screencast.com/t/GjBSMP3a |   | do you see any benefit to have in on yes or no? |   |   |  
 
  | greg | 10:09:10 pm |  
 
  | great yea... that being said, comet cache recommends this on but it obviously causes that issue. see here https://www.screencast.com/t/GjBSMP3ado you see any benefit to have in on yes or no? | great yea... |   | that being said, comet cache recommends this on but it obviously causes that issue. see here https://www.screencast.com/t/GjBSMP3a |   | do you see any benefit to have in on yes or no? |   |  
great yea... |  
that being said, comet cache recommends this on but it obviously causes that issue. see here https://www.screencast.com/t/GjBSMP3a |  
do you see any benefit to have in on yes or no? |  
 
 
 
Majid Hamdani10:12:01 pm This i'm not really sure about if adding the / is causing issues against what you are trying to achievethen I guess you shouldn't keep them |   |   | Majid Hamdani | 10:12:01 pm |   |   |   | This i'm not really sure about if adding the / is causing issues against what you are trying to achievethen I guess you shouldn't keep them | This i'm not really sure about |   | if adding the / is causing issues against what you are trying to achieve |   | then I guess you shouldn't keep them |   |   |  
 
  | Majid Hamdani | 10:12:01 pm |  
 
  | This i'm not really sure about if adding the / is causing issues against what you are trying to achievethen I guess you shouldn't keep them | This i'm not really sure about |   | if adding the / is causing issues against what you are trying to achieve |   | then I guess you shouldn't keep them |   |  
This i'm not really sure about |  
if adding the / is causing issues against what you are trying to achieve |  
then I guess you shouldn't keep them |  
 
 
 
greg10:12:46 pm ok...i just came across this https://github.com/websharks/comet-cache/issues/554 i will check it out more...in the meantime it seems to be ok...perhaps I will read up on this issue and ask them more about it too.10:13:29 pmthanks for you help:)that should do it for now |   |   | greg | 10:12:46 pm |   |   |   | ok...i just came across this https://github.com/websharks/comet-cache/issues/554 i will check it out more...in the meantime it seems to be ok...perhaps I will read up on this issue and ask them more about it too.10:13:29 pmthanks for you help:)that should do it for now | ok...i just came across this https://github.com/websharks/comet-cache/issues/554 |   | i will check it out more...in the meantime it seems to be ok...perhaps I will read up on this issue and ask them more about it too. | 10:13:29 pm | thanks for you help |   | :) |   | that should do it for now |   |   |  
 
  | greg | 10:12:46 pm |  
 
  | ok...i just came across this https://github.com/websharks/comet-cache/issues/554 i will check it out more...in the meantime it seems to be ok...perhaps I will read up on this issue and ask them more about it too.10:13:29 pmthanks for you help:)that should do it for now | ok...i just came across this https://github.com/websharks/comet-cache/issues/554 |   | i will check it out more...in the meantime it seems to be ok...perhaps I will read up on this issue and ask them more about it too. | 10:13:29 pm | thanks for you help |   | :) |   | that should do it for now |   |  
ok...i just came across this https://github.com/websharks/comet-cache/issues/554 |  
i will check it out more...in the meantime it seems to be ok...perhaps I will read up on this issue and ask them more about it too. | 10:13:29 pm
thanks for you help |  
:) |  
that should do it for now |  
 
 
 
Majid Hamdani10:13:49 pm sure thing :) have a good night |   |   | Majid Hamdani | 10:13:49 pm |   |   |   | sure thing :) have a good night | sure thing :) |   | have a good night
 
  | Majid Hamdani | 10:13:49 pm |  
 
  | sure thing :) have a good night | sure thing :) |   | have a good night
sure thing :) |  
have a good night

------

Let me know what you think...

Greg

**Comment by raamdev** [comment] 2017-09-02 17:56
@gwfc That chat log is pretty unreadable with so much duplicated content... 

Comet Cache Pro adds one of two `.htaccess` snippets to your `.htaccess` file **when you enable the Apache Optimizations → Enforce Canonical URLs option**. I emphasize that because by default Comet Cache does not insert anything into the `.htaccess` file. If you're having trouble with this option in your setup, I would recommend simply leaving that option disabled.

- Enforce Canonical URLs (No Trailing Slash): https://github.com/websharks/comet-cache-pro/blob/170220/src/includes/templates/htaccess/canonical-urls-no-ts-enable.txt

- Enforce Canonical URLs (Trailing Slash): https://github.com/websharks/comet-cache-pro/blob/170220/src/includes/templates/htaccess/canonical-urls-ts-enable.txt

If there's a specific bug related to Multisite and that option, I'll gladly file a bug report so that we can get that fixed in a future release.

----

@renzms Could you please attempt to reproduce this issue in a Multisite environment when you get a chance and provide a detailed report of the issue?

**Comment by gwfc** [comment] 2017-09-02 18:25
@raamdev 

Thanks. The video in the beginning illustrates the issue. Not sure why the chat pasted like that here.
But, it is definitely a bug per the video on WP multisites. I have it off for now but would like to turn back on in the future when/if it is fixed. :)

**Comment by renzms** [comment] 2017-09-12 18:08
Hi @gwfc 
I was not able to reproduce this issue on a clean Multisite Install for Sub-domains or Sub-directory Networks. Could you provide any more information regarding your Domain Mapping of your network or the hierarchy?

**Closed as completed** 2017-11-15 16:32 UTC
Labels: needs feedback
