### ISSUE TITLE
COMET_CACHE_EXCLUDE_HOSTS notice and warning in v160706

### ISSUE THREAD

**Issue by bridgeport** [wpsharks/comet-cache#811] opened 2016-08-05 17:37 UTC
Hi,

FYI, upgrading from Comet Cache Pro v160521 to v160706 results in the following debug.log notices and warning for each page that's cached:

```
[05-Aug-2016 17:23:48 UTC] PHP Notice:  Use of undefined constant COMET_CACHE_EXCLUDE_HOSTS - assumed 'COMET_CACHE_EXCLUDE_HOSTS' in /home/userdir/public_html/wp-content/plugins/comet-cache-pro/src/includes/traits/Ac/ObUtils.php on line 161
[05-Aug-2016 17:23:48 UTC] PHP Notice:  Use of undefined constant COMET_CACHE_EXCLUDE_HOSTS - assumed 'COMET_CACHE_EXCLUDE_HOSTS' in /home/userdir/public_html/wp-content/plugins/comet-cache-pro/src/includes/traits/Ac/ObUtils.php on line 161
[05-Aug-2016 17:23:48 UTC] PHP Warning:  preg_match(): Delimiter must not be alphanumeric or backslash in /home/userdir/public_html/wp-content/plugins/comet-cache-pro/src/includes/traits/Ac/ObUtils.php on line 161
```

**Comment by raamdev** [comment] 2016-08-05 18:18
@bridgeport Hmm, that's odd. Are you using `COMET_CACHE_EXCLUDE_HOSTS` anywhere to manually exclude specific hosts?

**Comment by bridgeport** [comment] 2016-08-05 18:24
@raamdev No I'm not using that constant anywhere. By the way, I'm on PHP 5.6.24, which I've been using since July 25, 2016.

I don't know if it's related, but I switched the PHP handler from mod_php (DSO) to FastCGI (FPM) a few weeks ago. Afterward, PHP executes as the owner of the file instead of Apache's nobody (group and user). During that time span I was still using v160521. I just upgraded to v160706 today and that's when the notices started building up. Only when a page cache file is created.

I downgraded to v160521 and the notices and warning went away.

**Comment by raamdev** [comment] 2016-08-06 00:48
@bridgeport Thank you. I see that `COMET_CACHE_EXCLUDE_HOSTS` was added in the last version, so it looks like we missed something somewhere. It's not obvious to me what we missed, but I'll do some more testing and get this fixed for the next release. Thanks for reporting!

**Comment by raamdev** [comment] 2016-09-06 02:22
@bridgeport I just ran a bunch of tests in attempt to reproduce this issue and I was not able to reproduce it. Based on the error you noted, I suspect this was related to there being an old version of the Comet Cache code in memory, cached via PHP's OPCache. If you can confirm that the server where you saw this occur has OPCache enabled, that would further confirm my theory. 

The error message said `Use of undefined constant COMET_CACHE_EXCLUDE_HOSTS`, however `COMET_CACHE_EXCLUDE_HOSTS` is present in Comet Cache v160706+ and loaded properly. The only reason you'd see that error message is if there was an old copy of the Comet Cache source code (from v160521, which _did not_ have `COMET_CACHE_EXCLUDE_HOSTS` defined) loaded in memory.

Clearing PHP's OPCache should resolve the issue. In Comet Cache v160521, we [addressed this issue](https://github.com/websharks/comet-cache/issues/740#issuecomment-218233197) by having Comet Cache automatically clear the OPCache after a plugin update, however it sounds like there might be some scenario that is not being accounted for.

If you update to the latest version of Comet Cache (v160709) and click the Clear OPCache button in the Admin Toolbar (see below), do you still experience the error?

![2016-09-05_22-20-42](https://cloud.githubusercontent.com/assets/53005/18259900/1747d388-73b7-11e6-84c9-73a1b3d9d56d.png)

**Comment by bridgeport** [comment] 2016-09-09 04:56
@raamdev Thanks for looking into this. Since experiencing this issue, I downgraded to v160521, which didn't log the notices and warning. The Comet Cache clear OpCache setting has always been enabled.

Several days after posting this issue, I disabled OpCache entirely as it apparently wasn't even caching anything. It was active and "running" but the cache was always empty with zero hits. Apparently OpCache has problems with PHP 7 using FastCGI as the PHP handler. Since php-fpm wasn't an available option, disabling the useless OpCache was necessary.

The clear OpCache setting within the Comet Cache options area is still active (forgot to disable it), but it seems harmless.

When the latest RC gets a final release, I'll try it in production to confirm if the issue I previously reported went away.

Thanks.

**Comment by raamdev** [comment] 2016-09-12 20:00
@bridgeport Great! Thank you for the update. If you could confirm this issue has gone away once the official next release comes out, that would be great. If there's still an issue, I'll revisit this for further investigation.

**Comment by bridgeport** [comment] 2016-10-01 18:30
@raamdev The issue has gone away for pro v160917. Thanks.

**Comment by raamdev** [comment] 2016-10-03 21:13
@bridgeport Thanks so much for following up. 😄  I'll go ahead and close this.

**Closed as completed by raamdev** 2016-10-03 21:13 UTC
Labels: cannot reproduce
