### ISSUE TITLE
TablePress calls to GLOBALS['quick_cache'] do not work

### ISSUE THREAD

**Issue by Kedakai** [wpsharks/comet-cache#694] opened 2016-02-27 23:27 UTC
I updated Comet Cache just now and tried if the Issue from https://github.com/websharks/comet-cache/issues/691 is solved. Still the exact same Problem..
Video was marked as private. If its needed please comment.

**Comment by raamdev** [comment] 2016-02-28 01:02
@Kedakai It looks like the problem is that TablePress is using `method_exists()` to check if `$GLOBALS['quick_cache']->clear_cache()` exists, however since that is really a Closure and not an actual method, `method_exists()` returns false which prevents the cache from being cleared.

We're switching over to PHP Traits in the codebase very soon and that will solve this problem (i.e., `method_exists()` will be able to find `$GLOBALS['quick_cache']->clear_cache()`).

---

In the meantime, here's what you can do to get TablePress to clear the cache whenever you update a table. We can hook into the `cachify_flush_cache` action that gets called whenever TablePress calls `_flush_caching_plugins_caches()`. 

Add the following file and directory:
`wp-content/mu-plugins/tablepress-clear-comet-cache.php`

``` php
/*
Plugin Name: TablePress Clear Comet Cache
Description: Clears the Comet Cache cache whenever TablePress is updated
Author: WebSharks, Inc.
Version: 1.0
Author URI: http://www.websharks-inc.com
*/
add_action('cachify_flush_cache', '__tablepress_clear_cache');

function __tablepress_clear_cache() {
    comet_cache::clear();
}
```

**Comment by raamdev** [comment] 2016-03-04 16:17
The Comet Cache codebase has been updated to use PHP Traits (see https://github.com/websharks/comet-cache/issues/635) so this issue should be fixed in the next release.

**Closed as completed by raamdev** 2016-03-04 16:17 UTC
Labels: compatibility
