### ISSUE TITLE
WPML Compatibility Bug When Languages Use Different Domain Names

### ISSUE THREAD

**Issue by VR51** [wpsharks/comet-cache#750] opened 2016-04-26 21:34 UTC
WPML allows admins to configure each language to use a URL that is either:
1. a query string
2. a virtual directory
3. a different domain name

When the clear cache button is clicked in Comet Cache Pro all caches are cleared for URL formats 1 and 2 but format 3 (different domain name) remains unwiped.

I think the cache does clear itself automatically when it expires (not 100% sure) but the Clear Cache button doesn't do the job when different domains are used per language. Manual deletion of the cache directory does work (lol).

I've tried clearing the cache with the button while logged into the affected language version of the site (2 languages only). Doesn't make a difference. The secondary domain's cache doesn't clear.

As this happens with WPML it might also happen with multisites that use domain mapping. That'll need to be tested.

Thanks guys!

**Comment by raamdev** [comment] 2016-04-27 13:55
@VR51 Can you give me an example of what a "different domain name" would be? For example, if your primary domain is `example.com` are you able to tell WPML to use `en.example.com`? And how does that work anyway? Is WPML adding something to your `.htaccess` file to rewrite URLs?

The reason the cache for the other domain isn't getting cleared is that Comet Cache doesn't know about it. It just knows about the domain you have configured in the WordPress settings.

**Comment by VR51** [comment] 2016-04-28 02:20
Hi raamdev, I kinda guessed the cause would be something along those lines.

Not certain it needs to perform rewrites for the multi-domain name feature to work. Certainly makes no edits to .htaccess. I'll explain how the server and WPML are configured:

We have two domain names, one for each language:
1. english-example.com
2. spanish-example.com

They are not sub-domains. The hyphens are deliberate.

The server is configured to use spanish-example.com as the root domain. english-example.com is an addon domain. Both domains point to the same server space.

WPML has an option for setting a domain name to use for the alternate language versions of the site.

When a request is made to the server, WPML detects which domain is requested. WordPress serves the requested page. WPML detects whether an alternate language version of the page exists and if one does then WPML displays a link to the alternate language version. The WordPress admin pages are served under the primary domain name.

Here is the WPML official explanation: https://wpml.org/faq/server-setting-for-languages-in-different-domains/

Thank you for looking into this.

**Comment by raamdev** [comment] 2016-04-28 13:27
@VR51 Ah, thank you very much for that explanation and the great link to the WPML docs.

We actually have another issue open (see https://github.com/websharks/comet-cache/issues/608) specifically related to aliased domains and this issue with WPML clarifies the problem a bit more, so we should be able to get this fixed sooner rather than later.

I've copied relevant information from this GitHub issue over to the other one; see https://github.com/websharks/comet-cache/issues/608#issuecomment-215421402.

_Note: If you're interested in testing a beta release of Comet Cache before the next version comes out, please sign-up to be a beta tester [here](http://cometcache.com/beta-testers/) or see **Comet Cache → Plugin Updater → Beta Testers** to automatically receive Release Candidate updates._

**Comment by VR51** [comment] 2016-04-28 17:51
Thank you Raam. Look forward to that update. Will register as a beta tester later today.

**Comment by raamdev** [comment] 2016-05-03 01:06
Referencing internal ticket: https://websharks.zendesk.com/agent/tickets/12400

**Comment by raamdev** [comment] 2016-11-15 02:41
Noting that Comet Cache v160706, which was released several months back, fixed [the issue with aliased domains](https://github.com/websharks/comet-cache/issues/608). I believe that resolves the issue described above with WPML. @VR51 Can you confirm?

**Comment by VR51** [comment] 2016-11-15 05:42
Yes and no. Mostly positive. This appears to be resolved but I had a customer approach me last week to say the bug had returned. I'm keeping my eye on it. The bug's revival could have been a temporary quirk. Thanks @raamdev

**Comment by raamdev** [comment] 2016-11-16 01:09
@VR51 Thanks for the update. I'll go ahead and close this issue for now then. If you confirm the issue is still there, I'll reopen this issue to investigate further.

**Closed as completed by raamdev** 2016-11-16 01:09 UTC
Labels: bug, compatibility

**Comment by VR51** [comment] 2016-11-16 15:13
Sounds good to me. Will keep you posted.
