### ISSUE TITLE
Auto-cache cron event fails to work or doesn't see sitemap

### ISSUE THREAD

**Issue by MarioKnight** [wpsharks/comet-cache#634] opened 2015-12-16 19:18 UTC
I installed v151216-RC, and where #613 seems to have been solved as I do not get the error as reported there, however the event itself does not perform as it did prior to v151114.  Pre-v151114, if I called the `_cron_zencache_auto_cache` event directly via WP-CLI, it would take ~10 minutes to run and cache every page within the sitemaps from https://missdream.org/sitemap_index.xml .  Now when doing the same, I get the success message within a couple of seconds, however no cache files are generated.  I don't get any errors of sitemaps not being found within ZCP, and I can browse them with no issues in my web browser.

**Comment by raamdev** [comment] 2015-12-16 19:40
@MarioKnight If you let the Auto-Cache Engine run via WP Cron itself (or manually run the event from inside WordPress using a plugin like WP Crontrol), does Auto-Cache Engine appear to work fine? If so, that would indicate some weirdness with calling it via WP-CLI (which we haven't tested at all yet).

**Comment by MarioKnight** [comment] 2015-12-16 20:58
I got pulled away into a bunch of other things, and I checked to see if WP Cron itself ran the event, and the cache appears to be what I would expect to see following a clean run of the event.  Now I'm curious as to what may or may not have led to this, because in the past month I've had #613 and #630 occur, and in prep for WP Core 4.4 (which I eventually updated to as well), WP-CLI was updated to 0.21.1 to be compatible.  I'm not sure if I should keep this open, open an issue within WP-CLI's GitHub, or put in a WP trac ticket.  I'll see if I can better time and test running the manual that I had been doing when WP Cron is not running the event.

**Comment by raamdev** [comment] 2015-12-17 12:44
@MarioKnight Cool, thanks for the update. Yeah, with so many version changes around the same time it's hard to say which one may have introduced the problem. I suggest setting up a test environment where you install the previous versions of WP-CLI, WP Core, and ZenCache that were working for you, then attempting to reproduce the issue after updating each one individually to see which piece might be at fault. 

I'll leave this GitHub issue open for now in case ZenCache is at fault here. :-)

**Comment by raamdev** [comment] 2016-11-22 17:11
Closing; unable to reproduce.

**Closed as completed by raamdev** 2016-11-22 17:11 UTC
Labels: cannot reproduce, needs feedback, auto-cache engine
