### ISSUE TITLE
Compat.: Theme Switcha + Comet Cache = Problems?

### ISSUE THREAD

**Issue by jaswrks** [wpsharks/comet-cache#857] opened 2016-12-06 11:51 UTC
See: https://wordpress.org/plugins/theme-switcha/ (only 300+ installs)

A customer writes...

> It appears that there is a huge incompatibility between them. If I desactivate your plugin, everything works. But with it activated, the theme change is like random.

> Working on some page, missing on others...

Referencing internal/private ticket:
https://app.intercom.io/a/apps/zbpo3mkk/inbox/me@jaswsinc.com/conversations/7107016488

**Comment by renzms** [comment] 2017-03-15 15:07
@raamdev @jaswrks 


### Unable to reproduce error with Comet Cache

However, the Theme Switcha Plugin seems to only work for Admin Users. Visiting the page as a logged out visitor does not show the theme has switched.


I think this is a limitation of the plugin itself as I have tested this even with Comet Cache disabled, and the results were the same.

Starting while logged in with Twenty Seventeen:
>![screen shot 2017-03-15 at 11 04 04 pm](https://cloud.githubusercontent.com/assets/13220018/23955072/d9d49dde-09d3-11e7-8199-eacf9e598d7e.png)



Using the plugin to switch to Twenty Thirteen:

>![screen shot 2017-03-15 at 10 59 16 pm](https://cloud.githubusercontent.com/assets/13220018/23954951/803d129c-09d3-11e7-91fc-a356cccf5c33.png)

Switch is only visible while logged in.

Selecting active themes in Theme Switcha Dashboard:

>![screen shot 2017-03-15 at 10 59 25 pm](https://cloud.githubusercontent.com/assets/13220018/23954955/822e0c64-09d3-11e7-8a06-2290a05eb53e.png)


After using the plugin to switch to Twenty Thirteen:

![screen shot 2017-03-15 at 11 00 08 pm](https://cloud.githubusercontent.com/assets/13220018/23955000/a09cb682-09d3-11e7-946b-9d12a437a06c.png)

Visiting while logged out still shows Twenty Seventeen:

![screen shot 2017-03-15 at 10 59 59 pm](https://cloud.githubusercontent.com/assets/13220018/23954979/9290e55e-09d3-11e7-9c3d-c5b8cab37ebe.png)

**Comment by raamdev** [comment] 2017-03-16 00:32
@renzms Thanks for testing. I'm going to close this as `cannot reproduce`.

**Closed as completed by raamdev** 2017-03-16 00:32 UTC
Labels: cannot reproduce
