### ISSUE TITLE
Yoast SEO Compatibility Testing

### ISSUE THREAD

**Issue by jaswrks** [wpsharks/comet-cache#847] opened 2016-11-03 18:55 UTC
Referencing internal/private ticket:
https://websharks.zendesk.com/agent/tickets/14784

A customer suggests that Yoast SEO + Comet Cache may not behave properly in all cases. Such as when user-specific caching is enabled together with certain features offered by Yoast SEO.

One symptom reported by this user is the automatic clearing of cache files on each pageview.

**Comment by raamdev** [comment] 2016-11-03 21:34
I installed Yoast SEO v3.7.1 on my test site (WordPress 4.6.1), enabled Comet Cache with Logged-In Users caching (Comet Cache Pro v160917), and I cannot see any problem at all.

When I browse the site as a logged-in user, the user cache (the `.u` directories) are created and the cache file (e.g., `213.html`) is inside each of the `.u` directories. I browsed several pages and the user cache remains in place as expected. I also looked at the HTML Source and monitored the cache file creation time:

```
Comet Cache file built for (http://example.com/; user token: 213) in 2.16868 seconds, on: Oct 28th, 2016 @ 9:56 pm UTC; via HTTP request.
```

That cache file creation time (`Oct 28th, 2016 @ 9:56 pm`) did not change when I refreshed the page. Even 10 minutes later, it had the same file creation time, which indicates that the cache file is not being recreated on each pageview.

---

It could certainly be that there's a specific Yoast SEO configuration that causes this issue, however with the default Yoast SEO settings, I'm not able to reproduce this problem at all. 

Needs further testing in other Yoast SEO configurations.

**Comment by renzms** [comment] 2016-11-26 05:39
@raamdev 

### Unable to reproduce error

WordPress Version: 4.6.1
Current WordPress Theme: Twenty Sixteen version 1.3
Theme Author: the WordPress team - https://wordpress.org/
Theme URI: https://wordpress.org/themes/twentysixteen/
Active Plugins: Comet Cache Pro v161119 || Yoast SEO Version 3.8

### Steps taken

- Installed Comet Cache Pro + Yoast SEO
- Setup up different Yoast Configurations
- Enabled Logged-In User caching + Automatic Cache Clearing
- Visited pages as logged-in user to generate cache
- Revisit pages to check if cache had updated upon repeat page views

### Observed Behaviour

Comet Cache Pro + Yoast SEO has no current specific configurations that would cause early user-specific cache clearing upon page view. The nonce causes the cache to expire early but not on each pageview.

**Comment by raamdev** [comment] 2016-11-26 20:41
@renzms Thank you for the additional testing. I'll go ahead and close this then as `cannot reproduce`, at least until we receive more details about how to reproduce the issue.

**Closed as completed by raamdev** 2016-11-26 20:41 UTC
Labels: bug, cannot reproduce, compatibility
