### ISSUE TITLE
Better connectivity with Stream?

### ISSUE THREAD

**Issue by MarioKnight** [wpsharks/comet-cache#667] opened 2016-02-03 16:47 UTC
I'm not sure how to best sum this up in the subject line, but I've noticed when using the Stream plugin ( https://wordpress.org/plugins/stream/ ), when ZenCache Pro is active, I see the following logged at least a couple times per minute the following two events are logged:

```
"crons_setup_on_wp_with_schedules" setting was updated
"crons_setup" setting was updated
```

This appears to happen whenever someone is logged in and has the WP dashboard open in a tab regardless of what they are doing.  Potentially the same two events are logged with every page load however I currently can't verify this.  As these can pile up very quickly, it is difficult to use the Stream plugin for its intended purpose of tracking all changes being made within WordPress.  These events are logged under "Settings --> Settings" context so filtering out this context can have the potential miss out on important changes also within that context.  I can confirm that these only appear when the ZenCache Pro plugin is active, as I had been working on a new website to properly test.  Since it only occurs with ZCP active, I figured I would start here before contacting the Stream devs.  Please let me know if you need anything else from my end.  Thank you!

**Comment by lkraav** [comment] 2016-02-03 17:10
This is almost certainly related to #653 

Stream helped me identify that weird things with cron were indeed happening.

**Comment by KTS915** [comment] 2016-02-04 18:16
@lkraav: Are you sure that Stream is not also _causing_ the problem?

I ask for two reasons. One is this thread: https://wordpress.org/support/topic/repeating-changes-from-cronjob-ip-filtering?replies=9

The other is that I myself stopped using Stream because it was causing all sorts of peculiar issues (including on sites with no caching running at all). I have had far superior results with Activity Log, WP Security Audit Log, and Simple History

**Comment by raamdev** [comment] 2016-02-05 20:25
@MarioKnight writes...

> I've noticed when using the Stream plugin ( https://wordpress.org/plugins/stream/ ), when ZenCache Pro is active, I see the following logged at least a couple times per minute the following two events are logged:

I just installed the Stream plugin alongside the latest version of ZenCache Pro and I'm not seeing anything logged "a couple times per minute".

It sounds to me like there's something else (other than the Stream plugin, although as @KTS915 noted, possibly including the Stream plugin) preventing ZenCache Pro from behaving as expected. 

As @lkraav noted, the symptoms sound exactly like what was reported in https://github.com/websharks/zencache/issues/653, however as I outlined extensively in that issue I'm not able to reproduce the problem at all, so I suspect there's either a plugin, theme, or possibly server configuration issue introducing a conflict that is preventing ZenCache from behaving as expected. 

Unless I can reproduce the issue in a test site, I have no way of diagnosing it. :-)

**Comment by MarioKnight** [comment] 2016-02-05 20:47
Interesting, especially since this site is as bare minimum as can be.  Does it continue to not log on the test site if the auto-cache is enabled?  If it does, hopefully that can help.  If not, then I'm going to try the plugins that @KTS915 mentioned and see how those work for me since I'm not overly attached to Stream.

**Comment by raamdev** [comment] 2016-02-05 23:07
@MarioKnight writes...

> Does it continue to not log on the test site if the auto-cache is enabled?

Correct. I have both the Auto-Cache Engine and the HTML Compressor enabled, along with the Stream plugin, and I'm not seeing any repetitive logs related to `crons_setup_on_wp_with_schedules` or `crons_setup`.

**Comment by lkraav** [comment] 2016-02-22 18:04
> Are you sure that Stream is not also causing the problem?

Yes. Today's comet-cache update brought the problem back as it overwrote my monkeypatch, and I disabled Stream to see what happens. Exactly the same thing keeps happening, every request causes a database write for a cron update. So it's not Stream.

I'm still strapped for time for going in depth on this. Will be sure to report back when I have something.

**Comment by raamdev** [comment] 2016-02-25 03:07
@lkraav Thanks for the update! I've reopened https://github.com/websharks/comet-cache/issues/653#issuecomment-188580394 so that we can look into that issue with the cron setup a bit more. Please post further any updates to that issue over there. :-)

**Comment by raamdev** [comment] 2016-11-22 17:08
Closing in favor of #653; I haven't been able to reproduce any issue with the Stream plugin.

**Closed as completed by raamdev** 2016-11-22 17:08 UTC
Labels: cannot reproduce
