### ISSUE TITLE
Feature Request: Auto-Cache Engine Scheduler

### ISSUE THREAD

**Issue by renzms** [wpsharks/comet-cache#891] opened 2017-05-25 13:36 UTC
Currently, the only custom controls over the **Auto-Cache Engine** is if a customer wants to specifically cache a list or URLs, and the **Auto-Cache Delay Timer** to delay the connection between each run of URLs it makes.

It would also be nice if it were possible to control when the **Auto-Cache Engine** runs at an interval. This feature could work similar to how the **Cache Cleanup Schedule** (Dashboard → Comet Cache Pro → Cache Expiration Time → Cache Cleanup Schedule) and allow for caching of files via WP Cron at specific intervals.

This way the ACE process can occur more or less frequently, depending on the specific needs of a customer or their server.

____

Referencing internal ticket: https://secure.helpscout.net/conversation/369994963/1241/

**Comment by ogessel** [comment] 2017-05-25 14:35
This would be a great idea.+ 1 from me

**Comment by raamdev** [comment] 2017-05-25 22:20
@renzms This is a duplicate of https://github.com/websharks/comet-cache/issues/293. I'm going to copy your comments over to that GitHub issue and close this one.

@ogessel Thanks for the +1! :-) If you'd like to do the same over there, that would be great. That way you'll get notified when updates to that feature request occur.

**Closed as completed by raamdev** 2017-05-25 22:20 UTC
Labels: duplicate
