### ISSUE TITLE
Cornerstone Plugin Compatibility

### ISSUE THREAD

**Issue by jaswrks** [wpsharks/comet-cache#886] opened 2017-04-20 04:10 UTC
A customer writes...

> Cornerstone is a page editor that comes with the X Theme by Themeco it basically allows more functionality to design how posts and pages are laid out, however for some reason Comet Cache prevents Cornerstone from loading, and am forced to disable the plugin when ever i need to make changes

Referencing internal/private ticket:
https://secure.helpscout.net/conversation/351920691/922/?folderId=1246818

**Comment by andysallis** [comment] 2017-04-20 07:22
As Requested here is the theme I am using that Comet Cache does not work with.
[x.zip](https://github.com/websharks/comet-cache/files/941081/x.zip)

**Comment by monokee** [comment] 2017-08-21 23:12
I just ran into this. Utilizing a URI exclusion pattern (/x/**) in the pro version of Comet Cache also does not help.
Any insights into where I can start looking for a fix @jaswrks ?

**Comment by renzms** [comment] 2017-08-22 11:44
Reported in Support

Referencing internal ticket [here](https://secure.helpscout.net/conversation/417814382/1906/)

**Comment by raamdev** [comment] 2017-09-02 17:50
@renzms If you could attempt to reproduce this for us and include a detailed report of the issue, that would be great.

**Comment by monokee** [comment] 2017-09-02 23:59
Even though I'm a pro customer, I'm not neccessarily expecting a perfect quick fix here. But if you have any pointers as to where I might start looking for the issue myself I'd really appreciate it. There have been some forum posts on themeco support about this but no public fix or workaround has been proposed from either side. I'd need some input from someone who knows the codebase to start looking into it though.

**Comment by renzms** [comment] 2017-09-04 14:04
### Unable to reproduce issue

**Comet Cache Pro and Cornerstone confirmed working while both are active and enabled.**

@raamdev 
______
### Tested Using the following:

WordPress Version: 4.8.1
Current WordPress Theme: Twenty Seventeen version 1.3

Active Plugins: Comet Cache™ Pro v170220 / Comet Cache™ Pro v170808-RC | Cornerstone Version 2.0.6
MySQL Version: 10.0.31-MariaDB-0ubuntu0.16.04.2

_____

After activating/enabling Comet Cache Pro and installing Cornerstone, I was able to launch Cornerstone successfully from the plugin itself.

>![comet cache v170220](https://user-images.githubusercontent.com/13220018/30029877-9b445a56-91bd-11e7-8634-7e99becbceaa.png)


The Cornerstone plugin was able to load and initialize properly.


>![cornerstone loads](https://user-images.githubusercontent.com/13220018/30029889-a21409d0-91bd-11e7-9fd0-7f70bc8f00fb.png)


>![cornerstone loads2](https://user-images.githubusercontent.com/13220018/30029891-a73e21b6-91bd-11e7-8e23-a8213eeb9518.png)


There was also no issue clicking and editing from a Page/Post itself.

>![edit with cornerstone](https://user-images.githubusercontent.com/13220018/30029895-abe650bc-91bd-11e7-80d6-631d08673af9.png)


I was able to edit/update/save/and add elements to Pages/Posts using Cornerstone without issue:

>![editing cornestone](https://user-images.githubusercontent.com/13220018/30029903-b3ac56d4-91bd-11e7-829c-b362d81877f6.png)




_**The following HTML notes show that Comet Cache is not caching when Cornerstone is active**_
```html 
<!-- Comet Cache is NOT caching this page, because `$_SERVER['REQUEST_METHOD']` is `POST`, `PUT`, `DELETE`, `HEAD`, `OPTIONS`, `TRACE` or `CONNECT`. These request methods should never (ever) be cached in any way. -->
```


>![html notes comet cache not caching](https://user-images.githubusercontent.com/13220018/30029989-02d30f00-91be-11e7-8cc0-b79d6a1f5a31.png)



___

### Additional Testing with HTML Compressor Active:

>![html compressor](https://user-images.githubusercontent.com/13220018/30029914-bff385d4-91bd-11e7-99a6-8e1432effb2c.png)


>![elements - cornerstone](https://user-images.githubusercontent.com/13220018/30029915-c4115650-91bd-11e7-957d-884dcfa50f02.png)

No issues found with both plugins active, Cornerstone loaded successfully and I was able to update elements using Cornerstone.

On the front end, the Comet Cache Pro plugin works normally and caches for non-logged in users.

>![html notes front end](https://user-images.githubusercontent.com/13220018/30029925-cced8fa0-91bd-11e7-9cd8-0bcc44a4e049.png)

**Comment by raamdev** [comment] 2017-09-09 22:36
@monokee @andysallis Please see @renzms's testing report above. He wasn't able to reproduce any issue with the Cornerstone plugin.

I'm going to close this issue, but if you can update us with a few steps to reproduce the issue in a [clean WordPress installation](https://cometcache.com/kb-article/testing-comet-cache-in-a-clean-wordpress-installation/), I can reopen this for further testing.

**Closed as completed by raamdev** 2017-09-09 22:36 UTC
Labels: cannot reproduce, compatibility

**Comment by Pixel8rx** [comment] 2017-10-13 08:43
I still have a problem with launching Cornerstone while Comet Cache is active.

I am using X v 5.2.2 & Cornerstone v2.1.3, when I try to start Cornerstone to edit a page when Comet Cache is active it won't start. If I then dectivate Comet Cache it loads just fine. 

Prehaps you could test this using the X theme, which is the theme that Cornerstone is supplied with, rather than the Twenty Seventeen one.

**Comment by monokee** [comment] 2017-10-13 08:58
When bundled with Themeco's X and Pro themes, Cornerstone is not installed to the wordpress plugin directory but integrated into the theme codebase and likely configured differently than a separate plugin installation - which absolutely won't make this any simpler to debug. :/

**Comment by dtwist** [comment] 2018-07-17 10:56
I encountered this issue on one of the sites we manage (we host dozens of x/pro sites, and most of them use Comet cache without issue.)

I tracked the problem down to Comet Cache's setting "Apache optimizations » Enforce Canonical URLs", which adds the following to the site's .htaccess file:

```
# Force a trailing slash on all virtual requests (except WP admin area).
<IfModule rewrite_module>
  RewriteEngine On
  RewriteBase /

  # If not a real file or directory.
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME} !-d

  # Not a part of the WP admin area.
  RewriteCond %{REQUEST_URI} !(?:^|/)wp\-admin(?:/|$)

  # Not a REST request, which never redirects.
  RewriteCond %{REQUEST_URI} !(?:^|/)wp-json(?:/|$)

  # If there is no trailing slash.
  RewriteCond %{REQUEST_URI} !/$

  # Force a trailing slash on all virtual requests.
  RewriteRule ^(.*)$ $1/ [QSA,L,R=301]
</IfModule>
```

Cornerstone POSTs JSON payloads to the URI "/cornerstone-endpoint", and expects a JSON response. With the Comet Cache setting enabled, these POSTs are being 301 redirected to a GET at the canonicalized URI "/cornerstone-endpoint/" (adds the trailing slash).

Modifying the .htaccess code manually to include a condition requiring the request be a GET if it is to be rewritten solves the problem:

```
  # Only capture GET requests
  RewriteCond %{REQUEST_METHOD}  =GET
```

(The full rules then look as follows)

```
# Force a trailing slash on all virtual requests (except WP admin area).
<IfModule rewrite_module>
  RewriteEngine On
  RewriteBase /

  # If not a real file or directory.
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME} !-d

  # Not a part of the WP admin area.
  RewriteCond %{REQUEST_URI} !(?:^|/)wp\-admin(?:/|$)

  # Not a REST request, which never redirects.
  RewriteCond %{REQUEST_URI} !(?:^|/)wp-json(?:/|$)

  # If there is no trailing slash.
  RewriteCond %{REQUEST_URI} !/$

  # Only capture GET requests
  RewriteCond %{REQUEST_METHOD}  =GET

  # Force a trailing slash on all virtual requests.
  RewriteRule ^(.*)$ $1/ [QSA,L,R=301]
</IfModule>
```
